### ISSUE TITLE
need support for creating releases with file groups

### ISSUE THREAD

**Issue by maryamklabib** [pivotal-cf/pivnet-resource#107]
### Context
The PKS Releng team uses the pivnet-resource in order to upload a PKS release to Pivnet.
Currently, our PM has to manually go in and create folders, and place our CLI dependencies in each folder.

Our metadata looks something like

```
product_files:
- file: tile/content/pks-linux-amd64-VERSION
  upload_as: PKS CLI - Linux
  file_type: "Software"
- file: tile/content/pks-darwin-amd64-VERSION
  upload_as: PKS CLI - Mac
  file_type: "Software"
- file: tile/content/kubectl-linux-amd64-VERSION
  upload_as: Kubectl VERSION - Linux
  file_type: "Software"
- file: tile/content/kubectl-darwin-amd64-VERSION
  upload_as: Kubectl VERSION - Mac
  file_type: "Software"
```

### Ask
We would like to be able to configure `file_groups` inside our pivnet metadata file and have our CLI dependencies show up as two folders, one that contains all PKS CLI files for all OSes, and one that has all Kubectl files for all OSes.

A proposed manifest could be something like

```
product_files:
  - file_groups:
      - name: PKS CLI VERSION
          - file: tile/content/pks-linux-amd64-VERSION
            upload_as: PKS CLI - Linux
            file_type: "Software"
          - file: tile/content/pks-darwin-amd64-VERSION
            upload_as: PKS CLI - Mac
            file_type: "Software"
      - name: Kubectl VERSION
          - file: tile/content/kubectl-linux-amd64-VERSION
            upload_as: Kubectl VERSION - Linux
            file_type: "Software"
          - file: tile/content/kubectl-darwin-amd64-VERSION
            upload_as: Kubectl VERSION - Mac
            file_type: "Software"
```

- Ramya (@rumshenoy) and Maryam
