### ISSUE TITLE
Debugging failures

### ISSUE THREAD

**Issue by professor** [pivotal-cf/pivnet-resource#115]
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2019/05/04 14:26:15 Exiting with error: cannot find specified release
```

I would love if this error message told me a little more about what to do next. Given the api token, what versions can the code see? Or what is the latest version it can see?

I had this working and I bumped the version number and it can't find the release even though I see it on pivnet.

**Comment by professor** [comment]
I was asking for
```
- name: untested-tile
  type: pivnet
  source:
    product_slug: pivotal-container-service
    api_token: ((dev-releases-pivnet-token))
    product_version: 1\.4\.0\-build\.31
    sort_by: semver
```

And the resource could not find it. When I removed the product version, it successfully found the latest  `Minor Release` which was `1.4.0` -- I suspect that when converted `1.4.0-build.31` into a minor release, it is no longer discoverable by the original code. It would be nice from a concourse perspective if we could treat dev builds and minor builds the same.

Interestingly, this can't find the build either...

```
- name: untested-tile
  type: pivnet
  source:
    api_token: ((dev-releases-pivnet-token))
    product_slug: pivotal-container-service
    product_version: 1\.4\.0
    sort_by: semver
```
