### ISSUE TITLE
release type breaks version

### ISSUE THREAD

**Issue by pnikonowicz** [pivotal-cf/pivnet-resource#121]
using version:
```
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
```

with the following configuration:
```
- name: pas-tile-2.8
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: elastic-runtime
    product_version: 2.8.*
    release_type: Security Release
```

Expected: 
no results should match

Actual:
![image](https://user-images.githubusercontent.com/1413657/67684005-c21b6100-f968-11e9-8cfc-bce2a583cdb3.png)

Context:
PAS 2.8 has not been released yet to the public.
We use a refresh token that can see all PAS Dev Releases.
There are 2.8 versions available but there are no 2.8 versions that are `publicly` available.
