### ISSUE TITLE
Unnecessary trigger 

### ISSUE THREAD

**Issue by a-bardai** [pivotal-cf/pivnet-resource#124]
Hi All,
We have a pipeline that is supposed to trigger based on pivnet product versions. But lately we are seeing strange behavior with it. Below is part of the pipeline:
```
resource_types:
  - name: pivnet
    type: docker-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: latest-final

resources:
  - name: product
    type: pivnet
    source:
      api_token: ((pivnet_token))
      product_slug: ((product_slug))
      product_version: ((product_version))

jobs:
  - name: acquire-lock
    serial: true
    plan: 
      - get: product
        params:
          globs: 
          - ((product_glob))
        trigger: true
      - put: locks
        params: 
          claim: upload
 - name: upload-and-stage-tile
    serial: true
    plan:
      - in_parallel:
          - get: locks
            passed: 
              - acquire-lock
          - get: product
            params: 
              globs:
                - ((product_glob))
            passed: 
              - acquire-lock
            trigger: true
```
The 'acquire-lock' was triggered even though there was not a new version of the product. However, the 'upload-and-stage-tile' did not, which has the same criteria for trigger as 'acquire-lock'.

Any ideas why this would be?
