### ISSUE TITLE
Skips dev versions once there is a release candidate

### ISSUE THREAD

**Issue by professor** [pivotal-cf/pivnet-resource#128]
We've been using the following concourse resource to get each dev build of pks off of pivnet:
```
- name: dev-pivotal-container-service-1-7
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: pivotal-container-service
    product_version: 1\.7\..*
```

Once there were release candidates, the pivnet resource no longer saw any dev builds =(
```
1.7.0-build.5#2020-01-20T07:25:17.280Z
1.7.0-build.7#2020-01-30T01:55:11.395Z
1.7.0-build.11#2020-02-26T07:20:35.854Z
1.7.0-build.12#2020-02-27T11:21:48.624Z
1.7.0-build.16#2020-03-04T20:53:32.578Z 
1.7.0-rc.1#2020-03-04T20:53:32.578Z (which is build.16)
1.7.0-rc.2#2020-03-13T18:35:25.208Z (which is build.19)
1.7.0-rc.3#2020-03-31T17:54:35.840Z 
1.7.0#2020-03-31T17:54:35.840Z (which is build.26)

Note that there are build.21, build.22, build.24, build.25
```

I'm wondering what is the correct configuration to get each dev tile. I was tempted to add a `    sort_by: last_updated` ... but would that have unintended consequences if people modify metadata on a tile in pivnet.
