### ISSUE TITLE
Dependencies and upgrades not populated

### ISSUE THREAD

**Issue by scottfrederick** [pivotal-cf/pivnet-resource#36]
I am building a metadata file for publishing to PivNet that includes a large number of `dependencies` and a few `upgrade_paths`. The `put` to the pivnet resource succeeds, but none of the dependencies or upgrade paths are getting populated in the PivNet UI. I'm hoping you can take a look at the metadata and see if you can spot anything wrong? 

The release created in PivNet with this metadata is at https://network.pivotal.io/products/p-spring-cloud-services/releases/2390/edit. 

Here's the yaml (warning, LOTS of dependencies!): 

```
---
release:
  version: "1.0.14"
  release_type: "Maintenance Release"
  release_date: "2016-10-05"
  eula_slug: "pivotal_software_eula"
  description: "Support for OpsManager & Elastic Runtime 1.6.x (and above)"
  release_notes_url: http://docs.pivotal.io/spring-cloud-services/release-notes.html
  availability: "Admins Only"
  controlled: false
  eccn: "5D002"
  license_exception: "ENC Unrestricted"
  end_of_support_date: "2018-10-05"
  end_of_guidance_date: "2018-10-05"
  end_of_availability_date: "2018-10-05"
product_files:
- file: tile-data/p-spring-cloud-services-1.0.14.pivotal
  Upload_as: "Spring Cloud Services Product Installer"
  description: "Spring Cloud Services Product Installer, providing Config Server, Service Registry, and Circuit Breaker Dashboard."
dependencies:
- release:
    id: 2330
    version: 1.7.14
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2263
    version: 1.7.13
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2186
    version: 1.7.12
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2125
    version: 1.7.11
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2098
    version: 1.7.10
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1962
    version: 1.7.9
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1915
    version: 1.7.8
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1883
    version: 1.7.7
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1862
    version: 1.7.6
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1818
    version: 1.7.5.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1782
    version: 1.7.4.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1768
    version: 1.7.3.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1754
    version: 1.7.2.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1745
    version: 1.7.1.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1691
    version: 1.7.0.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2370
    version: 1.6.23
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2329
    version: 1.6.22
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2256
    version: 1.6.21
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2219
    version: 1.6.20
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1955
    version: 1.6.18
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2119
    version: 1.6.19
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1926
    version: 1.6.17
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1880
    version: 1.6.16
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1855
    version: 1.6.15
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1767
    version: 1.6.14.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1740
    version: 1.6.13.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1589
    version: 1.6.12.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1526
    version: 1.6.11.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1508
    version: 1.6.10.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1413
    version: 1.6.9.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1371
    version: 1.6.8.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1329
    version: 1.6.7.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1196
    version: 1.6.6
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 1136
    version: 1.6.5
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 704
    version: 1.6.4
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 684
    version: 1.6.3
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 662
    version: 1.6.2
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 621
    version: 1.6.1
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 588
    version: 1.6.0
    product:
      id: 78
      name: Pivotal Cloud Foundry Operations Manager
- release:
    id: 2359
    version: 1.7.25
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2345
    version: 1.7.24
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2325
    version: 1.7.23
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2283
    version: 1.7.22
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2262
    version: 1.7.21
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2222
    version: 1.7.20
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2201
    version: 1.7.19
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2178
    version: 1.7.18
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2162
    version: 1.7.17
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2141
    version: 1.7.16
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2134
    version: 1.7.15
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2090
    version: 1.7.14
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2046
    version: 1.7.13
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2028
    version: 1.7.12
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2005
    version: 1.7.11
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1994
    version: 1.7.10
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1975
    version: 1.7.9
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1951
    version: 1.7.8
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1908
    version: 1.7.7
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1875
    version: 1.7.6
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1854
    version: 1.7.5
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1831
    version: 1.7.4
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1805
    version: 1.7.3
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1775
    version: 1.7.2
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1730
    version: 1.7.1
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1706
    version: 1.7.0
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2353
    version: 1.6.42
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2323
    version: 1.6.41
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2261
    version: 1.6.40
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2223
    version: 1.6.39
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2209
    version: 1.6.38
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2123
    version: 1.6.37
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2091
    version: 1.6.36
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2052
    version: 1.6.35
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2029
    version: 1.6.34
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2004
    version: 1.6.33
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1991
    version: 1.6.32
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1973
    version: 1.6.31
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1952
    version: 1.6.30
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1909
    version: 1.6.29
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1874
    version: 1.6.28
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1853
    version: 1.6.27
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1829
    version: 1.6.26
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1803
    version: 1.6.25
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1727
    version: 1.6.23
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1714
    version: 1.6.22
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1686
    version: 1.6.21
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1645
    version: 1.6.20
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1612
    version: 1.6.19
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1584
    version: 1.6.18
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1530
    version: 1.6.17
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1485
    version: 1.6.15
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1395
    version: 1.6.14
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1357
    version: 1.6.13
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1344
    version: 1.6.12
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1231
    version: 1.6.11
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1207
    version: 1.6.10
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 1189
    version: 1.6.9
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 731
    version: 1.6.8
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 724
    version: 1.6.7
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 703
    version: 1.6.6
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 685
    version: 1.6.5
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 679
    version: 1.6.4
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 666
    version: 1.6.3
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 639
    version: 1.6.2
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 614
    version: 1.6.1
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 608
    version: 1.6.0
    product:
      id: 60
      name: Pivotal Cloud Foundry Elastic Runtime
- release:
    id: 2328
    version: 1.6.7
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 2139
    version: 1.6.6
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 2105
    version: 1.6.5
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 2017
    version: 1.6.4
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 1972
    version: 1.6.3
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 1882
    version: 1.6.2
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 1845
    version: 1.6.1
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 1799
    version: 1.6.0
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 2327
    version: 1.5.15
    product:
      id: 4
      name: RabbitMQ for PCF
- release:
    id: 2384
    version: 1.7.15
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2341
    version: 1.7.14
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2306
    version: 1.7.13
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2132
    version: 1.7.12
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2057
    version: 1.7.11
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1959
    version: 1.7.10
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1898
    version: 1.7.9
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1770
    version: 1.7.8
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1731
    version: 1.7.7
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1578
    version: 1.7.6
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1525
    version: 1.7.5
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1509
    version: 1.7.4
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1410
    version: 1.7.3
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1327
    version: 1.7.2
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1195
    version: 1.7.1
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 718
    version: 1.7.0.4
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 700
    version: 1.7.0.3
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 656
    version: 1.7.0.2
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 635
    version: 1.7.0.1
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 601
    version: 1.7.0.0
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2378
    version: 1.6.17
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2335
    version: 1.6.16
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2301
    version: 1.6.15
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 2131
    version: 1.6.14
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1956
    version: 1.6.13
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1895
    version: 1.6.12
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1769
    version: 1.6.11
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1728
    version: 1.6.10
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1576
    version: 1.6.9
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1519
    version: 1.6.8
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1507
    version: 1.6.7
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1409
    version: 1.6.6
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1326
    version: 1.6.5
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 1194
    version: 1.6.4
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 716
    version: 1.6.3.4
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 698
    version: 1.6.3.3
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 654
    version: 1.6.3.2
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 634
    version: 1.6.3.1
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 576
    version: 1.6.3.0
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 498
    version: 1.6.2.0
    product:
      id: 41
      name: MySQL for PCF
- release:
    id: 460
    version: 1.6.1.0
    product:
      id: 41
      name: MySQL for PCF
upgrade_paths:
- release:
    id: 2338
    version: 1.0.13
- release:
    id: 2116
    version: 1.0.12
- release:
    id: 1977
    version: 1.0.11
- release:
    id: 1881
    version: 1.0.10
- release:
    id: 1735
    version: 1.0.9
- release:
    id: 1668
    version: 1.0.8
- release:
    id: 1582
    version: 1.0.7
- release:
    id: 1581
    version: 1.0.6
- release:
    id: 1524
    version: 1.0.5
- release:
    id: 1415
    version: 1.0.4
- release:
    id: 1188
    version: 1.0.3
- release:
    id: 694
    version: 1.0.2
- release:
    id: 657
    version: 1.0.1
- release:
    id: 603
    version: 1.0.0
```
