### ISSUE TITLE
need support for file groups

### ISSUE THREAD

**Issue by echobravopapa** [pivotal-cf/pivnet-resource#42]
While enhancing our pipeline to download Gemfire at the moment it was needed we discovered that the pivnet-resource did not support file groups.
trying to download Gemfire 8.2.1, which I know I can use the PivNet API and goto https://network.pivotal.io/products/pivotal-gemfire#/releases/1753/file_groups/429  where the release # and filegroup # are the key factors...
Gemfire releases several archives per release targeted for various platforms, in development we need to be able to get a specific one, i.e. Pivotal_GemFire_821_b18207_Linux.tar.gz

We are using resource_types:

```
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
```

```
- name: gemfire-current
  type: pivnet
  source:
    api_token: {{token}}
    product_slug: pivotal-gemfire
    product_version: 8.2.1
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{awe-secret-access-key}}
```

```
- name: build-linux-debug
  serial: false
  plan:
  - do:
    - aggregate:
        ...
      - get: gemfire-current
        trigger: false
```
