### ISSUE TITLE
Support dependency specifiers

### ISSUE THREAD

**Issue by scottfrederick** [pivotal-cf/pivnet-resource#52]
The PivNet API now supports dependency specifiers as an alternative to specifying discrete dependencies: https://network.pivotal.io/docs/api#public/docs/api/v2/release_dependency_specifiers.md. 

It would be awesome if this were supported in the pivnet resource metadata.

**Comment by robdimsdale** [comment]
@scottfrederick agreed. We had a placeholder story to add this, but we will use this issue to drive out this feature.

There's some interesting behavior around `dependency specifiers` on pivnet, but from the perspective of the `pivnet-resource` it's actually quite simple: they are basically just associated metadata (similar to `dependencies`).

This will look as follows:

### In

`in` will additionally write the new top-level key `dependency_specifiers` to the `metadata` files as follows:

```yaml
---
release: ...
product_files: [ ... ]
dependency_specifiers:
- product_slug: foo-product
  specifier: 1.2.*
- product_slug: stemcells
  specifier: 3312.*
```

### Out

`out` will optionally support a new top-level key `dependency_specifiers` in the `metadata` file as follows:

```yaml
---
release: ...
product_files: [ ... ]
dependency_specifiers:
- product_slug: foo-product
  specifier: 1.2.*
- product_slug: stemcells
  specifier: 3312.*
```

For a given `dependency_specifier` both `product_slug` and `specifier` are required.

Does this fit the use-case you have in mind?
