### ISSUE TITLE
Feature request: specify glob in source configuration

### ISSUE THREAD

**Issue by peterellisjones** [pivotal-cf/pivnet-resource#53]
Hi,

We have a concourse pipeline continuously upgrading PCF — the pivnet-resource has made this much easier than it would have been without it, but today we ran into the following issue: 

We're using the following stemcell with ERT:

```
- name: pn-stemcell-ert
  type: pivnet
  source:
    api_token: {{pivnet_api}}
    product_slug: stemcells
    product_version: 3233.*
```

Which we are fetching with:

```
- get: pn-stemcell-ert
  trigger: true
  params:
    globs:
    - "bosh-stemcell-*-vsphere-esxi-ubuntu-trusty-go_agent.tgz"
```

Unfortunately our pipeline broke recently when [3233.7](https://network.pivotal.io/products/stemcells#/releases/3310) was released. This is because 3233.7 only contains the Azure stemcell.

![screen shot 2016-12-09 at 09 33 37](https://cloud.githubusercontent.com/assets/2788556/21044295/2a3c2328-bdf3-11e6-83c1-22a20be620a5.png)

As a fix we'll have to peg our stemcell to the older version [3233.6](https://network.pivotal.io/products/stemcells#/releases/3244) since that contains the VSphere and AWS stemcells we need, and then remember to remove this constraint when stemcells for our IAAS are released for version 3233.7 or later

![screen shot 2016-12-09 at 09 33 43](https://cloud.githubusercontent.com/assets/2788556/21044327/50dce6a2-bdf3-11e6-93d6-6d47148b6d85.png)

It would be great if we could specify a glob in the source configuration to only increment versions of resources when the new version contains files matching certain globs. eg:

```
- name: pn-stemcell-ert
  type: pivnet
  source:
    api_token: {{pivnet_api}}
    product_slug: stemcells
    product_version: 3233.*
    globs:
    - "bosh-stemcell-*-vsphere-esxi-ubuntu-trusty-go_agent.tgz"
    - "light-bosh-stemcell-*-aws-xen-hvm-ubuntu-trusty-go_agent.tgz"
```

cheers,

Pete
