### ISSUE TITLE
Pivnet download sitting at file not found. 

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pivnet-resource#92]
Trying to download ops-manager 2.x resource hangs with file not found error:

![image](https://user-images.githubusercontent.com/2275490/36905163-d1261ad8-1def-11e8-864c-d624d8703d53.png)

![image](https://user-images.githubusercontent.com/2275490/36905144-c6046bbe-1def-11e8-832e-f8d47e50323e.png)

```
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: pivnet-opsmgr
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager

jobs:
  - name: upgrade-opsmgr
    plan:
    - aggregate:
      - get: pcf-pipelines
      - get: govc
      - get: tool-pivnet-cli
        params: {globs: ["*linux_amd64*"]}
      - get: tool-om
        params: {globs: ["*linux*"]}
      - get: pivnet-opsmgr
        params: {globs: ["*.ova"]}
```
